# Generated by Django 4.0.5 on 2022-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHome', '0002_alter_proveedor_num_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='num_contacto',
            field=models.CharField(max_length=100),
        ),
    ]
