# Generated by Django 4.0.5 on 2022-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHome', '0003_alter_proveedor_num_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.CharField(max_length=100)),
                ('persona_contacto', models.CharField(max_length=250)),
                ('num_contacto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
