# Generated by Django 4.0.5 on 2022-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHome', '0006_tipo_enlace_sitios_bandwitch_sitios_tipo_enlace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitios',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='sitios',
            name='num_cliente',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sitios',
            name='ubicacion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
