# Generated by Django 4.0.5 on 2022-07-28 18:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebHome', '0007_remove_sitios_descripcion_sitios_num_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitios',
            name='bandwitch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitios',
            name='num_cliente',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sitios',
            name='proveedor_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebHome.proveedor'),
        ),
        migrations.AlterField(
            model_name='sitios',
            name='tipo_enlace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebHome.tipo_enlace'),
        ),
        migrations.AlterField(
            model_name='sitios',
            name='ubicacion',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', ckeditor.fields.RichTextField()),
                ('num', models.IntegerField()),
                ('contact', models.CharField(max_length=150)),
                ('proveedor', models.CharField(max_length=150)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebHome.sitios')),
            ],
        ),
    ]
