# Generated by Django 4.0.5 on 2022-07-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebHome', '0008_alter_sitios_bandwitch_alter_sitios_num_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamos',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='WebHome.sitios'),
        ),
    ]
