# Generated by Django 4.0.5 on 2022-07-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebHome', '0010_alter_reclamos_sitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamos',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebHome.sitios'),
        ),
    ]
