# Generated by Django 4.0.5 on 2022-07-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebHome', '0011_alter_reclamos_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamos',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebHome.proveedor'),
        ),
    ]
